name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  
jobs:
  k8s:
    name: CI - k8s
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: update tools
        run: |
          #kind
          echo ---------------------------------------------------------------
          echo kind - installing ...
          echo ---------------------------------------------------------------
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          echo "downloaded $(./kind --version)"

          BIN_DIR=$HOME/.kind/bin
          mkdir -p $BIN_DIR
          mv ./kind $BIN_DIR
          echo "$BIN_DIR" >> ${GITHUB_PATH}
          echo ---------------------------------------------------------------
      -
        name: update kubectl
        run: |
          #kubectl
          echo ---------------------------------------------------------------
          echo kubectl - installing ...
          echo ---------------------------------------------------------------
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          echo "downloaded kubectl: $(./kubectl version --short --client)"

          BIN_DIR=$HOME/.kubectl/bin
          mkdir -p $BIN_DIR
          mv ./kubectl $BIN_DIR
          echo "$BIN_DIR" >> ${GITHUB_PATH}
          echo ---------------------------------------------------------------
      -
        name: check tools
        run: |
          echo ---------------------------------------------------------------
          echo "$(kind --version)"
          echo ---------------------------------------------------------------
          echo "kubectl $(kubectl version --short --client)"
          echo ---------------------------------------------------------------
      -
        name: test-k8s
        run: |
          echo ---------------------------------------------------------------
          echo K8S Smoke Test
          echo ---------------------------------------------------------------
          .scripts/k8s-ci.sh dev
