name: Subgraph Publish
on:
  push:
    branches: [ main ]
    paths:
      - "subgraphs/**"

jobs:
  subgraph-publish:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - subgraph: "products"
            routing_url: "http://products:4000/graphql"
            rover-version: "latest"
          - subgraph: "users"
            routing_url: "http://users:4000/graphql"
            rover-version: "latest"
          - subgraph: "inventory"
            routing_url: "http://inventory:4000/graphql"
            rover-version: "latest"
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      GRAPH_REF: supergraph-router@dev

    name: ${{ matrix.subgraph }}

    steps:
      - uses: actions/checkout@v2
      - name: install rover
        env:
          ROVER_VERSION: ${{ matrix.rover-version }}
        run: |
          curl -sSL https://rover.apollo.dev/nix/$ROVER_VERSION | sh
          echo "PATH=$PATH:$HOME/.rover/bin" >> ${GITHUB_ENV}
      - name: check
        run: rover subgraph check $GRAPH_REF --schema subgraphs/dev/${{ matrix.subgraph }}/${{ matrix.subgraph }}.graphql --name ${{ matrix.subgraph }}
      - name: publish
        run: rover subgraph publish $GRAPH_REF --routing-url ${{ matrix.routing_url }} --schema subgraphs/dev/${{ matrix.subgraph }}/${{ matrix.subgraph }}.graphql --name ${{ matrix.subgraph }}
